name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: sahrulm
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif
          
      - name: Generate Snake Game Animation
        uses: Platane/snk@master
        id: snake-game
        with:
          github_user_name: sahrulm
          svg_out_path: dist/github-contribution-grid-snake-game.svg
          
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation"
